apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cpfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/cpfs"
    options:
      server: "192.168.0.1@tcp"
      fileSystem: "cpfs"
