apiVersion: v1
kind: Pod
metadata:
  name: "flexvolume-cpfs-example"
spec:
  containers:
    - name: "nginx"
      image: "nginx"
      volumeMounts:
          - name: pvc-cpfs
            mountPath: "/data"
  volumes:
  - name: pvc-cpfs
    persistentVolumeClaim:
        claimName: pvc-cpfs
