apiVersion: v1
kind: Pod
metadata:
  name: "flexvolume-alicloud-example"
spec:
  containers:
    - name: "nginx"
      image: "nginx"
      volumeMounts:
          - name: pvc-disk
            mountPath: "/data"
  volumes:
  - name: pvc-disk
    persistentVolumeClaim:
        claimName: pvc-disk
