apiVersion: v1
kind: Pod
metadata:
  name: "flexvolume-alicloud-example"
spec:
  containers:
    - name: "nginx"
      image: "nginx"
      volumeMounts:
        - name: "d-bp1au6l6mbscl64apz0n"
          mountPath: "/var/lib"
  volumes:
    - name: "d-bp1au6l6mbscl64apz0n"
      flexVolume:
        driver: "alicloud/disk"
        fsType: "ext4"
        options:
          volumeId: "d-bp1au6l6mbscl64apz0n"
